// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Comment           string
	CommentLike       string
	Friendship        string
	Image             string
	ImageVariation    string
	Like              string
	Post              string
	User              string
	UserHasFriendship string
}{
	Comment:           "comment",
	CommentLike:       "comment_like",
	Friendship:        "friendship",
	Image:             "image",
	ImageVariation:    "image_variation",
	Like:              "like",
	Post:              "post",
	User:              "user",
	UserHasFriendship: "user_has_friendship",
}
